package com.corejava.demo.abstraction;

public class Assignment0425 {
	// CREATE A CLASS CALLED BANKING
	// DECLARE METHODS OF CREDIT AND DEBIT
	// DECLARE AND INTERFACE CALLED AS ISO90001
	// DECLARE FEW CONTRACTS IN ISO90001
	// CREATE A BANK - BOA
	// CREATE ANOTHER BANK - CITI
	// EXTEND BANKING AND IMPLEMENT ISO90001
	// USE THE METHODS DECLARED IN BANKING FOR BOA AND CITI 
	// USE POLYMORPHIC BEHAVIOR WHEREVER NECESSARY
}
